"""New relationships added

Revision ID: 56b79ca8d419
Revises: 7c0823847643
Create Date: 2023-02-05 09:08:06.028057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b79ca8d419'
down_revision = '7c0823847643'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
