"""Nova coluna tamanhos

Revision ID: 7c0823847643
Revises: 928e2a68c490
Create Date: 2023-02-05 08:33:18.030484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0823847643'
down_revision = '928e2a68c490'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('tamanhos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'tamanhos')
    # ### end Alembic commands ###
