"""Fixed Relationshiop classes

Revision ID: 91520dfaa340
Revises: 9b17757eff2b
Create Date: 2023-02-09 08:47:04.381762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91520dfaa340'
down_revision = '9b17757eff2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.drop_column('commnets')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commnets', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
