"""Initial commit

Revision ID: 928e2a68c490
Revises: 
Create Date: 2023-02-05 08:28:35.083802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e2a68c490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
