"""Senha to Password name column

Revision ID: b55a4b87c8f9
Revises: 91520dfaa340
Create Date: 2023-03-05 12:45:23.206176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55a4b87c8f9'
down_revision = '91520dfaa340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
