"""Changed name of column Tamanhos

Revision ID: df87ef76f95e
Revises: 1e17bb7944da
Create Date: 2023-02-05 17:07:29.613130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df87ef76f95e'
down_revision = '1e17bb7944da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))
        batch_op.drop_column('tamanhos')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanhos', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('size')

    # ### end Alembic commands ###
